---
zookeeper_version: 3.4.10
zookeeper_user: zookeeper
zookeeper_group: zookeeper
zookeeper_conf_dir: /etc/zookeeper/conf
zookeeper_log_dir: /var/log/zookeeper
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_maxClientCnxns: 50
