---
- name: Get disk alignment for disk {{ item }}
  shell: if [[ -e /sys/block/{{ item }}/queue/optimal_io_size && -e /sys/block/{{ item }}/alignment_offset && -e /sys/block/{{ item }}/queue/physical_block_size ]]; then echo $[$(( ($(cat /sys/block/{{ item }}/queue/optimal_io_size) + $(cat /sys/block/{{ item }}/alignment_offset)) / $(cat /sys/block/{{ item }}/queue/physical_block_size) )) | 2048]; else echo 2048; fi
  when: ansible_devices[item] is defined
  register: disk_offset

- name: Partition disk {{ item }}
  shell: parted -s -a optimal /dev/{{ item }} mklabel gpt mkpart primary xfs {{ disk_offset.stdout|default("2048") }}s 100% && sleep 5 && partprobe /dev/{{ item }}; sleep 5
  when: ansible_devices[item] is defined and ansible_devices[item]['partitions'] == {}

- name: Create the filesystem on disk {{ item }}
  filesystem: dev="/dev/{{ item }}1" fstype="xfs"
  when: ansible_devices[item] is defined
